import type { Metadata } from "next";
import "../../app/globals.css";
import { Poppins } from 'next/font/google';
import AppProvider from "@/components/providers/AppProviders";
import Navbar from "@/components/Shared/Header/navbar";
import Footer from "@/components/Shared/Footer/Footer";

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '700'], // Add desired font weights
    variable: '--font-poppins', // Optional: Define a CSS variable
});



export const metadata: Metadata = {
    title: "lilitile",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AppProvider>
            <html lang="en">
                <body className={poppins.className}>
                    <div>
                        <Navbar />
                    </div>
                    {children}

                    <div>
                        <Footer />
                    </div>
                </body>
            </html>
        </AppProvider>
    );
}
